### ISSUE TITLE
Cppcheck 2.13 on Ubuntu 24.04 leads to `constParameterCallback` on pre-commit hook

### ISSUE THREAD

**Issue by blueskyson** [sysprog21/fibdrv#16]
## Environment
- Cppcheck Version: 2.13
- Operating System: Ubuntu 24.04
- Linux Version: Linux aspire7 6.8.0-38-generic #38-Ubuntu SMP PREEMPT_DYNAMIC Fri Jun  7 15:25:01 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

## How to Reproduce

The following output shows up after adding changes and executing the git commit:

```
fibdrv.c:75:33: style: Parameter 'offset' can be declared as pointer to const. However it seems that 'fib_read' is a callback function, if 'offset' is declared with const you might also need to cast function pointer(s). [constParameterCallback]
                        loff_t *offset)
                                ^
fibdrv.c:114:13: note: You might need to cast the function pointer here
    .read = fib_read,
            ^
fibdrv.c:75:33: note: Parameter 'offset' can be declared as pointer to const
                        loff_t *offset)
                                ^
nofile:0:0: information: Active checkers: 106/592 (use --checkers-report=<filename> to see details) [checkersReport]

Fail to pass static analysis.
```

## Proposed Solution

Add `--suppress=constParameterCallback:fibdrv.c` to the Cppcheck commandline options.

**Comment by jserv** [comment]
> Proposed Solution
> Add `--suppress=constParameterCallback:fibdrv.c` to the Cppcheck commandline options.

It sounds great. Send a pull request.

**Comment by blueskyson** [comment]
How about adding the Ubuntu 24.04 environment to the GitHub Action workflow?

**Comment by jserv** [comment]
> How about adding the Ubuntu 24.04 environment to the GitHub Action workflow?

Good idea. Please proceed.
