### ISSUE TITLE
Make error causes by diff

### ISSUE THREAD

**Issue by ghost** [sysprog21/fibdrv#4]
Error occur while doing `make check` after I change fib_write() (the `out` file will be different with `scripts/expected.txt`)
```
@diff -u out scripts/expected.txt && $(call pass)
```
make: *** [Makefile:40：check] 錯誤 1
The proccess will stop.

Instead of removing the line, I modify it to
```
-@diff -u out scripts/expected.txt && $(call pass)
```
the error will be ignored.
make: [Makefile:40：check] 錯誤 1 (已忽略）
And the proccess will therefore continue.

**Comment by jserv** [comment]
If you use different criteria for testing, the file `expected` should be refined.

**Comment by ghost** [comment]
Got it. I will refine `expected` then.
